trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:  
    - job: First Job
      steps:
        - bash: echo build FirstJob
    - job: Second Job
      steps:
        - bash: echo Build SecondJob
- stage: DevDeploy
  jobs:  
    - job: DevDeploy Job
      steps:
        - bash: echo build DevDeploy Job
- stage: QADeploy
  jobs:  
    - job: QADeploy Job
      steps:
        - bash: echo build QADeploy Job
- stage: ProdDeploy
  jobs:  
    - job: ProdDeploy Job
      steps:
        - bash: echo build ProdDeploy Job
                